apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:94GVTlNHEUYkCJEIjUWVlg4dKK01xwuRnIYTKcAtWn/wvtRqSa1x0rUbRI8l30HdECLRbpkwqNnIJY5Qs5hLMsGP5weB8HnWfElxOK4YGZzhwuecmkJ5bN8cNvfve5fRLtWZtGcfXXuz30qQxYruk5i8zw/P8WP6mWB0K7+jX+Q9usDkOLdTJYg=,iv:YVnzbG+tx7Mr9Mi2GdT09T4jEC5TU2VjhDBGwFaKV2s=,tag:F4+pChoUdTdQ23j+/PqLfA==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:GscFoe0=,iv:JWQvtp6mP3EOlrlERdsiMrLDNGo63f06yD83iv6nqNs=,tag:AtH3d7okwe7IbSPu7QsoYQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:6bwjatwbw246QNiaLCLMP/ERutih2c6KWuci0S/LNic=,iv:xrJx/81fC8Op8wob0pER2BAStGXI2qanKaf9Sh4GdCQ=,tag:JMiGUryozxCcn3eEz6NrYw==,type:str]
sops:
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMmlMKzFzczJQTkZNam9L
            ajdUV3BESENyWWdYbGtMUXlRWjRVd2dETmlZCllia2dHVk1wSERaalZTeEEvZmVl
            SEZTK3BKK0JuZVNjQkNSSmpwNTFHb1kKLS0tIERwVk1MWXlSZHAxaTlXTE1JL050
            RDd2U0drbEdBSlUzM2tqNllwdFV1bUUKpHodzy+B3c17l6MXv4yCxMwVyOeZS0qU
            UFNWn45CooTgqw8LQWrntXaGLfupe2caifsRa4py0JyTufgYZHZGig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T20:34:35Z"
    mac: ENC[AES256_GCM,data:rLwLvvMYwJoQggpz+6ZmdDeW+4dBvs2C80GGYKQoxDtb8Smn0RmoNesG8PIMV94NbYbjPGBvG/Yayh1sf+2GaT7lMdFZWl5+VqRDCDj7/T4uauHPtn9R5yF/2uOb46xeVjW5eko5m6+r6UklXecWRPHU5zzvSOnq+EAN2v6Rj1Q=,iv:xPKMH/9eYpx3x43J9/t1EPQaGbTyJfetpIAYXOP1/Kg=,tag:4Q/oFECH4EvVv/V39tr9PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
