apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:GscFoe0=,iv:JWQvtp6mP3EOlrlERdsiMrLDNGo63f06yD83iv6nqNs=,tag:AtH3d7okwe7IbSPu7QsoYQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:6bwjatwbw246QNiaLCLMP/ERutih2c6KWuci0S/LNic=,iv:xrJx/81fC8Op8wob0pER2BAStGXI2qanKaf9Sh4GdCQ=,tag:JMiGUryozxCcn3eEz6NrYw==,type:str]
sops:
  age:
    - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMmlMKzFzczJQTkZNam9L
        ajdUV3BESENyWWdYbGtMUXlRWjRVd2dETmlZCllia2dHVk1wSERaalZTeEEvZmVl
        SEZTK3BKK0JuZVNjQkNSSmpwNTFHb1kKLS0tIERwVk1MWXlSZHAxaTlXTE1JL050
        RDd2U0drbEdBSlUzM2tqNllwdFV1bUUKpHodzy+B3c17l6MXv4yCxMwVyOeZS0qU
        UFNWn45CooTgqw8LQWrntXaGLfupe2caifsRa4py0JyTufgYZHZGig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T00:16:50Z"
  mac: ENC[AES256_GCM,data:gSwVFXEAAha2qOYTtTzC5XDQPaaumltJPZ3ahs0ZAZOKMOLd7FYL+jKLamekWYOjAz3o0Nl8xUoZlHbmVMuMYiispZCKWg6vOUoXr7DSqpUz/BYYrk5qRYFAskppfqx7vQmY5gH67KZ1fQbGxV6Y1fggIpXw3f2URcOaVaf13yE=,iv:LFaI48MG4I9UaURk3FffC6OuRZuCBcBN+uVdakQ9ZGU=,tag:UvUGPv8VBvvRjcpmfLoOYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
