apiVersion: v1
kind: Secret
metadata:
    name: spoolman-secret
stringData:
    SPOOLMAN_DB_HOST: ENC[AES256_GCM,data:ibyuoZbnYbCLVWSXKWMrEdpuIVbn32D770/5wJsjMxF4Ew==,iv:33+79KOw9Wq36UVdDM4EACWI7TtW9tnr373Bc8K7dSQ=,tag:O5IeA8ybG9l86OVxrcB7Og==,type:str]
    SPOOLMAN_DB_PORT: ENC[AES256_GCM,data:Ag5Lyw==,iv:5j72OaI6BghJxbYJmllDhufP2rKnWFN2e175yNB7FIE=,tag:C4RnHF5w3PGRk/ql5Znnhg==,type:str]
    SPOOLMAN_DB_TYPE: ENC[AES256_GCM,data:kJD0hPuJqA0=,iv:WalatG+dvBPD929Ja1svvCYxygNxOLzsztziynCjDag=,tag:1+dMJWlC9MaC2s2qoM6yjA==,type:str]
    SPOOLMAN_DB_NAME: ENC[AES256_GCM,data:B7hisDGmca8=,iv:zo4cOylF7RLg54ktYUUoFqCWS4VzKoDXUOL+AracKyM=,tag:u4xjoPzoFS/a0l8KKUglIw==,type:str]
    SPOOLMAN_DB_USERNAME: ENC[AES256_GCM,data:F0gMV1UbJxI=,iv:iJ/p+CQbu1gQr37UhZJS3sNNRmp75gbJcAzPb5+5f/8=,tag:keo3mRQXT+zIaz5oL3Df1A==,type:str]
    SPOOLMAN_DB_PASSWORD: ENC[AES256_GCM,data:pNUPqZkIDbdau7CpseyPBuuqybXNkZ7PziLI564cXSg=,iv:FYHt/29mWlFPUPLsBq2nDXKI06cEcb/gzAt6cuyK9o0=,tag:DgSZ4302DG/doffzpnLMpA==,type:str]
    SPOOLMAN_METRICS_ENABLED: ENC[AES256_GCM,data:suHwsA==,iv:LKqhL5quNrJxHwcuuxqetRw6qlWsWhN/FojejfBFsFU=,tag:OxVhDI8BjW62JA855ITFKw==,type:str]
sops:
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMVliL3dYK01RYkZ0YVBY
            TjZsUnVKclZlU25QeEdXM25kTlJMVXBkNTJFCk4yaThWc0ZDaFA3cXBLbjF3R0x6
            OGY2b05UMnZYWUxLcnlsT1ViMWxFbk0KLS0tIHN0dTN0M2ZPSlVVZENwMEZBK3I1
            eDRSUm9XRkRJMkZ6T2llS3dYY3Jid2cKIfzmEgv02gSnJerAx0iB4+i0s4Hb5sfX
            NDngSVouDeaxEltj0jtnEIpIgdkqTw0dnkHUR/yf/LtfWMn8x9F1FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T20:31:46Z"
    mac: ENC[AES256_GCM,data:rsEEBnH8/txYR3+wjj4cKYooBfpdwO79pt2upFwirjjnsa+qYEar1ROfhzyDfqSOFWFsrUTvt/DW8P1GuNvyRt2gySdQSuxfGEvImZaHkhcmxBn5eNoA7pDL2NMB4ZpZ/SRzyT+1OaMldqSgmUIfgeJMTG+qZXnNqsXpqUQvt/M=,iv:e/1zIGFDepy/vWhhfo5RwSBSRIbz8mAXFleaNgJBMvE=,tag:48gvhjE3b0gbj/EquKFCNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
