apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LWNe+sibfFjDHSUa4w==,iv:Peu+wUQZiVSpfpwBBF572wKSJUy/F4AhfsCmzckCfBA=,tag:qbKCjk7iSutfSqFjmw2NTg==,type:str]
    SECRET_DOMAIN_INT: ENC[AES256_GCM,data:VWtw/rKLz3fJDcAG/qC8,iv:IKTeEgOVxPLzT8shqLR03RScfkLhmWZs891DXA7VRJI=,tag:dfOIPt2ZDHNsQiZAc2RY5w==,type:str]
    SECRET_AD_ENDPOINT: ENC[AES256_GCM,data:t1LubIyw6Ylm+2LUNctjRHhzPPWT/8PTBQ==,iv:lb/z0GpS0GNQLI7nEflih38gU+PxrKuey/rHNuG7pFY=,tag:C5dbaMPzk+aU7rewlaoNyg==,type:str]
    SECRET_AD_BASEDN: ENC[AES256_GCM,data:3mJHuO3GkeG6J82OEkez+Sj388QZNHgB,iv:TIjGfDeTDCKWt8OMRe20gWlYAilS3XrhJHTNErjo52c=,tag:7savlaeL3MDJoEPIa9C3kQ==,type:str]
    SECRET_DOT_UPSTREAM_NAME: ENC[AES256_GCM,data:GhIBqvz0l1zanWGPQB4MtvSvAKunA3PdQw1+xrQmf5hx,iv:Ij0Brcvm/NkFm8fczT+Bh7nDMu9mWaTzgUt8UTMd2GE=,tag:vOOLjThjvi/STYE47Zgbsw==,type:str]
    SECRET_MONITOR_KEY: ENC[AES256_GCM,data:PK6sKu8GUhUXwISPDemXkMY/WIAmH9pM22TNx+BmKMs=,iv:Cm0s5QyP5Pu5oGHrsUnAIJV0+06TZeQsT+wN9EECSlQ=,tag:OrBbBLriZFUhVKW6+V5Jtw==,type:str]
    SECRET_MONITOR_IP: ENC[AES256_GCM,data:mnFmCfw0FvvY/RzD,iv:FmWnjjVkUoYWAUoD8LcF7KwTOWd0pHsp8pq/bu9zk6o=,tag:LhellgZFipkf/tkTGFMLGA==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:OdaML2oULLlgDuBT3qfnmqPgOwMhymltH2HCLL1f,iv:/SUdXSNzmZp3WK3ZaYD4qBU5e7l2SIZWwg8uB0B4r8M=,tag:cOLzTrqT5CwlNVQ7wj208A==,type:str]
    SECRET_PUSHOVER_API_TOKEN: ENC[AES256_GCM,data:DnVKJVgnAYlUp7lH5zLCpkn6beSfYBmmdqJYHQ54,iv:Zuuv0DQG8xmPKSiZN4oXqeaszzxr+QuQl9EBBn2N68U=,tag:CLv+QomtBJeBCkwfhJSfHA==,type:str]
sops:
    age:
        - recipient: age1a68j5zasa55y39u5ecus7g4dzl3rqp0u6h6jwpuw3743cdf9dd4sykfhr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NDcvNE9oUXhJbEE0a3cz
            ZCtVbXoyRGZkYTZTM2R5UUlmVHRYK3JpSlVBCldkZFQ2MzV1SlZ5elhtL2xHT3ds
            QllFQ0JDb1MzU0hGVndySlRyU0Z1VXMKLS0tIGM1VWZqOER0MThCVjBnNW5aSnZt
            ZlBFRE5jRFFJUVp0L2cweFB0MGpudjgK6THfSbwmJDAUEcFNchLlKV5YPe9G4+BN
            /vCB5MXodL7Gg2EuoUEbNaFShfY6im6uWsLLOCrVperHP7UaXE0jxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T01:52:02Z"
    mac: ENC[AES256_GCM,data:jUjpZcrdUmhout4R7QCAW8di1upnrsF7gls0wjSVI06vSHGoKx5Ixc69AdK/6V5hW/FquE/lvaq6IENBbindXHD63lV7oHwC4Ya0QcW569h3U2jEgtpdP2DD5zwYyG0SXAtWLTKumkcBCmG1oaZMb7+tVOU00DALOWwwNJWu/gA=,iv:F4VwOwZ/+t2C6ClU8/2VxC3+XvyhBUoj52MUR26Hi5E=,tag:50a+JW6j1JqmHjnWDvg9Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
