---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &clusterName postgres17
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: longhorn-cluster-best-effort
    resizeInUseVolumes: false
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "128MB"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  nodeMaintenanceWindow:
    inProgress: false
    # prevent node drain issues with Longhorn strict-local volumes
    reusePVC: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 1
      destinationPath: s3://cloudnative-pg/
      endpointURL: "http://blackhole2.${SECRET_DOMAIN_INT}:3900"
      # Note: serverName version needs to be incremented
      # when recovering from an existing cnpg cluster
      serverName: postgres17-02
      s3Credentials:
        region:
          name: cloudnative-pg-garage-secret
          key: CNPG_S3_REGION
        accessKeyId:
          name: cloudnative-pg-garage-secret
          key: CNPG_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-garage-secret
          key: CNPG_S3_SECRET_ACCESS_KEY

  bootstrap:
    initdb:
      import:
        type: monolith
        databases: ["*"]
        roles: ["*"]
        source:
          externalCluster: postgres16-source

  externalClusters:
    - name: postgres16-source
      connectionParameters:
        host: postgres16-rw.db.svc.cluster.local
        user: postgres
        dbname: postgres
        port: "5432"
      password:
        name: postgres16-superuser
        key: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres17-daily
  namespace: db
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres17
